name: PowerShell-CI-Automation
on:
  push:
    branches: [ "main" ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Student Info
        run: |
          echo "Лабораторна робота №2"
          echo "Студент: Станіслав Бандура"
          echo "Виконано через PowerShell"

      - name: List Files
        run: ls -R
